# Generated by Django 3.1.6 on 2021-02-17 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0002_auto_20210217_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='xclass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='authentification.class'),
        ),
    ]
