# Generated by Django 3.1.6 on 2021-02-21 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0003_auto_20210217_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='task',
            field=models.CharField(default='task', max_length=200),
        ),
        migrations.AlterField(
            model_name='document',
            name='doc',
            field=models.FileField(blank=True, upload_to='eschool'),
        ),
    ]
